# Generated by Django 2.2.5 on 2019-11-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['price']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
